//go:build go1.18
// +build go1.18

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator. DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package fake

import (
	"encoding/json"
	"github.com/wbreza/azure-sdk-for-go/sdk/resourcemanager/machinelearning/armmachinelearning/v3"
)

func unmarshalExportSummaryClassification(rawMsg json.RawMessage) (armmachinelearning.ExportSummaryClassification, error) {
	if rawMsg == nil || string(rawMsg) == "null" {
		return nil, nil
	}
	var m map[string]any
	if err := json.Unmarshal(rawMsg, &m); err != nil {
		return nil, err
	}
	var b armmachinelearning.ExportSummaryClassification
	switch m["format"] {
	case string(armmachinelearning.ExportFormatTypeCSV):
		b = &armmachinelearning.CSVExportSummary{}
	case string(armmachinelearning.ExportFormatTypeCoco):
		b = &armmachinelearning.CocoExportSummary{}
	case string(armmachinelearning.ExportFormatTypeDataset):
		b = &armmachinelearning.DatasetExportSummary{}
	default:
		b = &armmachinelearning.ExportSummary{}
	}
	if err := json.Unmarshal(rawMsg, b); err != nil {
		return nil, err
	}
	return b, nil
}

